package com.example.db1.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * 


CREATE TABLE  user1(
	    id bigint generated by default as identity,
	    name varchar(255) NOT NULL,
	    age number(2) NOT NULL,
	    PRIMARY KEY (id)
	);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

 * @author FutechSoft
 *
 */ 

@Entity
public class User1 {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
     
    
    @Column
    private String name;
    
    @Column(name = "age")
    private Integer age;
    
    
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getAge() {
		return age;
	}
	public void setAge(Integer age) {
		this.age = age;
	}

    
    
    
}