

db1:
  datasource:
    jdbc-url: jdbc:h2:~/test  # H2 database URL
    driver-class-name: org.h2.Driver
    username: sa  # H2 default username
    password:  # H2 default password (empty)

spring:
  jpa:    
    hibernate:
      #naming:
       # physical-strategy: com.example.config.CustomPhysicalNamingStrategy  # Physical naming strategy
      ddl-auto: update  # Hibernate DDL auto strategy (update, create, create-drop, validate, none)
    show-sql: true  # Show SQL queries in console
    properties:
      hibernate:
        #physical-strategy: com.example.config.CustomPhysicalNamingStrategy  # Physical naming strategy
        dialect: org.hibernate.dialect.H2Dialect  # Hibernate dialect for H2
        format_sql: true  # Format SQL queries
        use_sql_comments: true  # Add SQL comments
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


sql:
  xml:
    locations: classpath:mappers/**/*.xml
    
